// actionTypes.js
export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';
export const SEARCH_CARS_REQUEST = 'SEARCH_CARS_REQUEST';
export const SEARCH_CARS_SUCCESS = 'SEARCH_CARS_SUCCESS';
export const SEARCH_CARS_FAILURE = 'SEARCH_CARS_FAILURE';
